---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "helloService"
  name: "hello-world-ballerina-v1"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 9091
    protocol: "TCP"
    targetPort: 9091
  selector:
    app: "helloService"
  type: "NodePort"
